### ISSUE TITLE
how to make sure to use male/female using human sprites?

### ISSUE THREAD

**Issue by martijnmichel** [DiceBear/avatars#100]
I'm implementing this wonderful library in my app and create avatars automatically for users by their displayName from firebase. 

When using @dicebear/avatars-avataaars-sprites how can I make sure the output is either male or female?

**Comment by FlorianKoerner** [comment]
You can do that with the options.

See:
- https://github.com/DiceBear/avatars/issues/21
- https://avatars.dicebear.com/styles/avataaars#npm

**Comment by seamive** [comment]
How can we achieve this? We have the same question, can you please give an example? Switching between genders?

```
import {createAvatar} from '@dicebear/avatars';
import * as style from '@dicebear/avatars-avataaars-sprites';
let svg = createAvatar(style, {
  seed: 'custom-seed',
  gender: 'male',
  // ... and other options
});
```

Help really appreciated. We tried this and doesn't seem to work.

Thanks!
