### ISSUE TITLE
Remarks on the README

### ISSUE THREAD

**Issue by PhiLhoSoft** [DiceBear/avatars#14]
I have two remarks / suggestions on your README of avatars-jdenticon-sprites:

One that applies to all sub-repos of your project: in English, _information_ is a mass noun, it doesn't take the plural. So the last title should read "Further information". (That's a mistake that, as a French, I made for a long time, that's why I am sensitive to it. :smile:)

And I suggest to give more... information in the options table. Perhaps by the used regexes, or by the available ranges.
Even if the error messages are explicit. I got _background must match the following: "/^#([0-9a-f]{3}|[0-9a-f]{6}|[0-9a-f]{8})$/i"_ (because I used # instead of %23) and _padding must be less than or equal to 0.2_ but it is better to indicate that explicitly in the doc.

Thanks for this very interesting library.

**Comment by FlorianKoerner** [comment]
Thanks for your feedback @PhiLhoSoft. I will take a closer look soon.

**Comment by FlorianKoerner** [comment]
I have added additional information to the Readme.

If you notice anything else, please feel free to mention it.

**Comment by PhiLhoSoft** [comment]
For my points, the update is excellent. Thanks.
