### ISSUE TITLE
sprites is not a function

### ISSUE THREAD

**Issue by infuzz** [DiceBear/avatars#18]
Hi, trying to use your great package but I'm facing a 'TypeError: sprites is not a function' when using it.

This is the way I did;
$ npm install --save @dicebear/avatars
$ npm install --save @dicebear/avatars-gridy-sprites

in js:
let avatars=require('@dicebear/avatars'),
let sprites=require('@dicebear/avatars-gridy-sprites')
let options = {};
let avatar = new avatars( sprites(options))
let svg = avatar.create('custom-seed')

And I got "TypeError: sprites is not a function"

Could you help me and point me where I'm wrong ?
Thank you !
Thierry

**Comment by FlorianKoerner** [comment]
You use `require` instead of es6 `import`.  With `require` you get back an object with the default export.

Accordingly, the following should work:

```js
let avatar = new avatars.default( sprites.default(options))
```

**Comment by infuzz** [comment]
Really thank you for your so quick answer !

Yes it works with this! 

`let avatar = new avatars.default( sprites.default(options))`

Thank you again for your fantastic avatar package and for your help.

Have a nice day !
