### ISSUE TITLE
Bottts - robot illustration generator

### ISSUE THREAD

**Issue by m5o** [DiceBear/avatars#20]
Just wanted to share - not sure if feasible…

https://bottts.com/

Create robot illustrations in Sketch App with this free library. Combine frames, antennas, sensors, accessories, and colors. 🤖

/cc @pablostanley

**Comment by FlorianKoerner** [comment]
Bottts fits perfectly! Will be officially supported in the coming weeks.

**Comment by FlorianKoerner** [comment]
Will be published this Thursday. :tada:

**Comment by FlorianKoerner** [comment]
Already available today!

**Comment by m5o** [comment]
Awesome @FlorianKoerner – Thank you, beautiful done 🙇‍♂️
