### ISSUE TITLE
Feature Request: a `sprites = human` 

### ISSUE THREAD

**Issue by xinbenlv** [DiceBear/avatars#31]
Hey,  @DiceBear you are awesome, very cute avatar! Kudos!

I am curious have you considered having a `sprites = human` option that (pseudo)randomly choose between male and female. I am building a website and needs a placeholder for people without image. I don't have gender information either so ideally if there can be a random one or even a gender-neutral option that would be awesome

**Comment by FlorianKoerner** [comment]
That's a good idea. I have officially added the Sprite Collection "human". This Sprite Collection randomly selects a gender. (https://github.com/DiceBear/avatars/tree/master/packages/avatars-human-sprites)

If you are looking for something more gender neutral, I can recommend the sprite collections "identicon", "botts", "avataaars", "gridy" and "jdenticon".
