### ISSUE TITLE
Icons stopped working?

### ISSUE THREAD

**Issue by atumas-bananamilk** [DiceBear/avatars#381]
We've been using this library for 3+ months.

Suddenly, new icons cannot be generated, old ones still work though (but parameters must be exact).
FYI the params for previously generated one must be all there, removing `backgroundType` makes the image empty too.

Same issue with `6.x` / `7.x` versions. What's the issue?

New one (any seed):
<img width="986" alt="Screenshot 2023-10-04 at 00 51 19" src="https://github.com/dicebear/dicebear/assets/22228431/b5d33df1-55cc-4f4b-baaa-c5f40b8e74b7">

Previously generated one (existing seed):
<img width="988" alt="Screenshot 2023-10-04 at 00 52 57" src="https://github.com/dicebear/dicebear/assets/22228431/935eefa0-14b0-4929-8a55-a3fb7e7d0709">

**Comment by FlorianKoerner** [comment]
There was an error in the server configuration here. It works again now. Sorry and thanks for pointing it out.

**Comment by FlorianKoerner** [comment]
I also adjusted the [monitoring](https://dicebear.betteruptime.com/) to be informed earlier in case of such errors. The error existed for four hours.
