### ISSUE TITLE
Encoded query parameters stopped working

### ISSUE THREAD

**Issue by ivmakk** [DiceBear/avatars#382]
Hi! 

Since today, I've noticed that encoded query parameters are causing 400 errors. Please let me know if there is a possibility of restoring support for encoded URIs in the API, or if I need to rebuild the URI generation in my app.

**Step to Reproduce**
* Open the link with an array in a query parameter, where the separator is encoded https://api.dicebear.com/7.x/bottts/svg?scale=95&eyes=bulging%2Ceva%2Cframe1%2Cframe2%2Cglow%2Chappy%2Crobocop%2CroundFrame01%2CroundFrame02%2Csensor%2Cshade01&backgroundColor=16171a&seed=51559cac-c179-48a7-b316-5bf48f83880e

**Expected Result**
* 200 code, image in response

**Current Result**
```
{
  "statusCode": 400,
  "code": "FST_ERR_VALIDATION",
  "error": "Bad Request",
  "message": "querystring/eyes/0 must be equal to one of the allowed values"
}
```

From what I see, if I open the same link without encoding (https://api.dicebear.com/7.x/bottts/svg?scale=95&eyes=bulging,eva,frame1,frame2,glow,happy,robocop,roundFrame01,roundFrame02,sensor,shade01&backgroundColor=16171a&seed=51559cac-c179-48a7-b316-5bf48f83880e), the encoded link starts to work too. I believe that's because of the once-generated image returned from the CDN cache.

**Comment by gburlet** [comment]
+1 also here because of this 400 error

**Comment by FlorianKoerner** [comment]
First of all, thank you for the detailed description of the problem. I have implemented a fix: https://github.com/dicebear/api/commit/1e8294aff643d80f665564799e43f96a0ea5ebfa

Can you confirm that it works again with this?

**Comment by gburlet** [comment]
Can confirm it's working for me again, thanks for fix!
