### ISSUE TITLE
HTTP API

### ISSUE THREAD

**Issue by AyoubCoding21** [DiceBear/avatars#384]
I've been using your API for a few months now, and then the identicons (https://avatars.dicebear.com/api/identicon/sth.svg) don't work they show an normal image without the icon.

**Comment by FlorianKoerner** [comment]
Hi @AyoubCoding21

You are using an outdated api url.

See:

- https://github.com/orgs/dicebear/discussions/374
- https://www.dicebear.com/how-to-use/http-api/
- https://www.dicebear.com/styles/identicon/
