### ISSUE TITLE
Issues with NextJS

### ISSUE THREAD

**Issue by Arinji2** [DiceBear/avatars#385]
I am getting weird errors even after trying out the workaround

This workaround doesnt seem to work for me. 
My packages
dependencies": {
    "@dicebear/collection": "^7.0.1",
    "@dicebear/converter": "^7.0.1",
    "@dicebear/core": "^7.0.1",
    "@spotify/web-api-ts-sdk": "^1.1.2",
    "lucide-react": "^0.288.0",
    "next": "^13.5.5",
    "pocketbase": "^0.18.3",
    "react": "^18",
    "react-dom": "^18",
    "react-toastify": "^9.1.3",
    "zod": "^3.22.4"
  },
  
  
  
![image](https://github.com/dicebear/dicebear/assets/87296817/04d81ec5-6ec1-4470-8c7d-f50e0633450d)

  
  Next Config
```js
 const path = require("path");
/** @type {import('next').NextConfig} */

const nextConfig = {
  experimental: {
    serverActions: true,
  },
  webpack: (config, { isServer }) => {
    config.resolve.alias["@dicebear/converter"] = path.resolve(
      __dirname,
      "node_modules/@dicebear/converter/lib/index.js"
    );

    return config;
  },
  reactStrictMode: false,
};

module.exports = nextConfig;

```

**Comment by FlorianKoerner** [comment]
Hi @Arinji2 

I'm sorry to hear that the workaround doesn't work for you.

To help you better, please provide me a repository with a small project where I can reproduce the bug.

**Comment by Arinji2** [comment]
I just used the http api :D 
Thanks anyways

**Comment by dclipca** [comment]
With `next.config.mjs` and `"next": "14.1.4"` (you have to `npm i @dicebear/converter`):

```ts
import path from 'path';
import { fileURLToPath } from 'url'; 

/** @type {import('next').NextConfig} */

// Convert the module URL to a directory path
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const nextConfig = {
  webpack: (config, { isServer }) => {
    config.resolve.alias["@dicebear/converter"] = path.resolve(
      __dirname,
      "node_modules/@dicebear/converter/lib/index.js"
    );

    return config;
  },
};
```
