### ISSUE TITLE
Help needed - Importing all avatar images

### ISSUE THREAD

**Issue by dhodapkarsoham** [DiceBear/avatars#39]
Hello,
I am working on a social media research project and want to use for Dicebear for getting profile images 'avatars'. I need all the avatar images so that I can let user select from any one of them. Is that possible?
Thanks, and I love Dicebear!

**Comment by FlorianKoerner** [comment]
You mean "avataaars"? The avatars are created dynamically. There are thousands of combinations. Maybe this is what you are looking for: https://getavataaars.com/
