### ISSUE TITLE
Irregular HTTP 504 status

### ISSUE THREAD

**Issue by bhagn** [DiceBear/avatars#390]
Here's the API i'm trying to use:

```
https://api.dicebear.com/7.x/fun-emoji/png?backgroundColor=b33771&mouth=cute,lilSmile,plain,shout,smileLol,smileTeeth,tongueOut,wideSmile,shout&seed=64d3854d495905b1bf50
```

This fails to generate the avatar and ultimately returns a 504 response. If I slightly change the `seed` (reduce the no. of chars) or remove the `backgroundColor` from the params, it seems to work. 

Is there some restriction on the URL length that's prohibiting the avatar generation?

**Comment by FlorianKoerner** [comment]
The server has problems converting this avatar as a PNG. SVG works.

I'll take a look at it later.

**Comment by Saacy** [comment]
Hello. I noticed the same PNG/SVG problem too for this seed:

```https://api.dicebear.com/7.x/bottts/svg?backgroundColor=ffdfbf&size=40&seed=d41907420dcaa44894d0a3e88476b0664dab805c```

PNG works, but not SVG.

**Comment by FlorianKoerner** [comment]
The firewall was blocking one of the CDN's IP addresses. Should now work reliably.

**Comment by bhagn** [comment]
Thanks for the quick turn around 👍🏼
