### ISSUE TITLE
502 Bad Gateway for a seed

### ISSUE THREAD

**Issue by Co-7** [DiceBear/avatars#391]
Hello,

I wanted to use the api and it works fine, but I noticed that for one of the words I was putting in I had a bad gateway.

seed: pantoufle

https://api.dicebear.com/7.x/lorelei/svg?seed=pantoufle

When I go to the url with this seed it gives me an error but I don't understand why.

Tanks for your help.

**Comment by FlorianKoerner** [comment]
The firewall was blocking one of the CDN's IP addresses. Should now work reliably.
