### ISSUE TITLE
Initials PNG format not working for Chinese Characters

### ISSUE THREAD

**Issue by skenan** [DiceBear/avatars#396]
Initials PNG format not working for Chinese Characters

works as expected for svg
https://api.dicebear.com/7.x/initials/svg?seed=你好

<img width="197" alt="image" src="https://github.com/dicebear/dicebear/assets/9022913/bf3eb00c-bfb1-4282-a26e-e543a808912f">

https://api.dicebear.com/7.x/initials/png?seed=你好

<img width="126" alt="image" src="https://github.com/dicebear/dicebear/assets/9022913/d8e205b4-9b6c-47be-a2d8-2e7d166e9016">

**Comment by FlorianKoerner** [comment]
Hi @skenan sorry for the late reply. Thanks for your feedback.

The HTTP-API now supports the following subsets: `cyrillic`, `cyrillic-ext`, `devanagari`, `greek`, `greek-ext`, `japanese`, `korean`, `latin`, `latin-ext`, `simplified-chinese`, `thai` and `vietnamese`. Hope this works for you.

![](https://api.dicebear.com/7.x/initials/png?seed=%E4%BD%A0%E5%A5%BD)
