### ISSUE TITLE
[Editor] Support a wider range of colors (especially skin tones)

### ISSUE THREAD

**Issue by lewxdev** [DiceBear/avatars#405]
I understand the original artists may have a recommended or original color palette, but I've found some of the choices limiting, especially when it comes to skin tones.

I propose, in addition to the existing individual colors, provide an optional slider of gradient colors to improve the customization

I think apple's Memoji editor handles this well, providing both individual colors and the spectrum they fall on
![Screenshot 2024-02-25 at 7 03 22 PM](https://github.com/dicebear/dicebear/assets/6710419/e36c043a-e8fc-4b7e-9414-02e8f5a2979d)

**Comment by FlorianKoerner** [comment]
Hi @lewxdev 

I like the idea. I'll see what I can do.

**Comment by diablade** [comment]
actually I already did it ... for myself
just use the `<ngx-colors/>` and wider skin palette
...

**Comment by FlorianKoerner** [comment]
@lewxdev I was able to implement your suggestion today. I'm sorry it took so long.

<img width="1005" alt="Bildschirmfoto 2024-06-24 um 22 20 19" src="https://github.com/dicebear/dicebear/assets/647303/709fab42-fca7-4da4-881a-60277090884e">
