### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by adrifm22** [DiceBear/avatars#406]
is the website down?

**Comment by FlorianKoerner** [comment]
It works for me:

- https://tools.keycdn.com/performance?url=https://www.dicebear.com
- https://dicebear.betteruptime.com/


Would you like to send me the URL you are trying to access and also your access region? We moved the domain to a new host yesterday. The name server update may take a little longer.

**Comment by adrifm22** [comment]
nevermind, now it's working :)

**Comment by Karnak19** [comment]
It's down for me: https://dicebear.com/

**Comment by adrifm22** [comment]
I tried again and it works with my data (from Spain).

But if I connect to thedata and wifi from france (were i am located right now), it doesn't work.

**Comment by FlorianKoerner** [comment]
I am very sorry that there are problems with the connection to DiceBear. I think we need to be patient until the new nameserver is known in all regions. It should only take a few more hours. The changeover took place 18 hours ago.

Please try again in a few hours and feel free to give me an update.

**Comment by FlorianKoerner** [comment]
Should be available again in the meantime.

**Comment by EMenardc** [comment]
Seems to be still down in Canada

**Comment by FlorianKoerner** [comment]
Hi @EMenardc 

To make sure that it is really still due to the name server update, would you like to check the output of the following commands?

---

Input:
```
dig ns dicebear.com
```

Output should include:
```
;; ANSWER SECTION:
dicebear.com.		85988	IN	NS	robotns3.second-ns.com.
dicebear.com.		85988	IN	NS	ns1.first-ns.de.
dicebear.com.		85988	IN	NS	robotns2.second-ns.de.
```

---

Input:
```
dig a dicebear.com
```

Output should include:
```
;; ANSWER SECTION:
dicebear.com.		86043	IN	A	49.12.146.164
```

---

If access to DiceBear is urgent, the following could help:

- DNS cache reset: https://blog.hubspot.com/website/flush-dns
- Alternative name server: https://1.1.1.1/

**Comment by FlorianKoerner** [comment]
The result from https://www.nslookup.io/domains/dicebear.com/dns-propagation/a/ looks good. Also for Canada.

**Comment by EMenardc** [comment]
Hi, 

here are the results

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> a dicebear.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 48083
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dicebear.com.                  IN      A

;; Query time: 149 msec
;; SERVER: 172.25.0.1#53(172.25.0.1) (UDP)
;; WHEN: Sat Mar 02 11:50:08 EST 2024
;; MSG SIZE  rcvd: 41

I seems to be my network, I tried using my phone LTE and it seems be working, 

Thanks

**Comment by FlorianKoerner** [comment]
Yes, it looks as if your network is not yet aware of the new name servers (`status: SERVFAIL`). In exceptional cases, it can take up to 72 hours until the name servers are known everywhere.

I'm really sorry about this. But it should work again for you in a short time.
