### ISSUE TITLE
Cannot convert SVG to PNG

### ISSUE THREAD

**Issue by aliusman** [DiceBear/avatars#41]
I am using C# to convert the SVG to PNG,

My scenario is the following
1. Load SVG file from URL into ContentStream
2. Convert it using to PNG using 'SVG' Nuget package
3. Save the PNG to MemoryStream
4. Upload it to Azure from MemoryStream

But the PNG is always broken // More details here https://stackoverflow.com/questions/58973984/svg-to-png-always-broken

**Comment by FlorianKoerner** [comment]
It looks like the SVG nuget package does not support masks.
https://github.com/vvvv/SVG/issues/482
