### ISSUE TITLE
How to ensure that viewboxMask are replaced with a random value when randomizeIds is enabled?

### ISSUE THREAD

**Issue by ASR-ASU** [DiceBear/avatars#411]
Hello,

When the `randomizeIds` parameter is set to `true`, the `viewboxMask` is replaced with a random value. However, it seems that this random value is not computed according to the given seed, due to the fact that a Prng instance is created using an empty string as seed (cf. https://github.com/dicebear/dicebear/blob/8.x/packages/%40dicebear/core/src/utils/svg.ts#L118).

Is my understanding correct? If yes, does reuse the options.seed or the Prng instance created here https://github.com/dicebear/dicebear/blob/8.x/packages/%40dicebear/core/src/core.ts#L20 could fix the issue?

**Comment by FlorianKoerner** [comment]
Hi @ASR-ASU 

You are right. I have just fixed that. Now real random values should be used.

Make sure you use one of the following versions:

- \>= 8.0.1
- \>= 7.1.2
- \>= 6.1.2
- \>= 5.4.2

Can you confirm that the problem has been solved?

**Comment by ASR-ASU** [comment]
Sound good. Thanks.

How to trigger the build of a new docker image (https://hub.docker.com/r/dicebear/api) ?

**Comment by FlorianKoerner** [comment]
I just released a new Docker image with the fix :)

https://hub.docker.com/layers/dicebear/api/2.3.1/images/sha256-e905e412b7b8af24e9a1de688eb11d6ad38b3f8cbaed0e41352bdbf4a99948a3?context=explore

```
docker run --read-only --tmpfs /run --tmpfs /tmp -p 3000:3000 -i -t dicebear/api:2.3.1
```

**Comment by ASR-ASU** [comment]
Thanks for your speed.
