### ISSUE TITLE
seed number failed

### ISSUE THREAD

**Issue by blocktock** [DiceBear/avatars#419]
https://api.dicebear.com/9.x/initials/svg?seed=1

Image cannot be displayed

**Comment by FlorianKoerner** [comment]
Hi @blocktock 

That is intentional. Only letters are considered as initials.
https://github.com/dicebear/dicebear/blob/9.x/packages/%40dicebear/initials/src/utils/initials.ts#L4

**Comment by blocktock** [comment]
您好：您的邮件我会尽快查看。祝您工作顺利！

**Comment by blocktock** [comment]
> Hi @blocktock
> 
> That is intentional. Only letters are considered as initials. https://github.com/dicebear/dicebear/blob/9.x/packages/%40dicebear/initials/src/utils/initials.ts#L4

Well, actually we still have digital avatars. Do you have any other solutions to support it

**Comment by FlorianKoerner** [comment]
Maybe I don't really understand the problem yet. An image should be displayed, but only one without initials - only with background color. Because numbers are not actually initials.

**Comment by FlorianKoerner** [comment]
The official API no longer supports numbers as initials. You would have to run the API yourself to support numbers or use the JS library in an older version.

- If you want to use the API solution, you have to create a fork and set the packages to version "8.0.1". https://github.com/dicebear/api/blob/2.x/versions/8.x/package.json#L10
- If you want to use the JS library, it must be version 8.0.1. There is a bug in 8.0.1 that interprets numbers as initials.
