### ISSUE TITLE
Docker image size is 3x larger on 2.5.0 than before

### ISSUE THREAD

**Issue by duriantang** [DiceBear/avatars#420]
I noticed that the recent version of the docker image has become a lot larger.

  2.3.2 122MB
  2.4.1 189MB
  2.5.0 583MB

please check on https://hub.docker.com/r/dicebear/api/tags

**Comment by FlorianKoerner** [comment]
Hi @duriantang 

Thank you for bringing this to my attention. This happened because all Noto Sans font weights were copied into the image, although only a handful are used. This has now been corrected and the size is now 197.54 MB.
