### ISSUE TITLE
NextJS toPng() function not working

### ISSUE THREAD

**Issue by JustZvan** [DiceBear/avatars#427]
```
        try {
            const gravatar = await axios.get(
                `https://gravatar.com/avatar/${emailHash}?d=404`,
                {
                    responseType: "arraybuffer",
                }
            );

            const buffer = Buffer.from(gravatar.data);

            avatarData = buffer;
        } catch {
            /*             const avatar = await axios.get(
                `https://api.dicebear.com/9.x/initials/png?seed=${fullName}`,
                {
                    responseType: "arraybuffer",
                }
            );

            const buffer = Buffer.from(avatar.data);

            avatarData = buffer; */

            const svg = createAvatar(initials, {
                seed: fullName,
            });

            const png = toPng(svg);

            console.log(await png.toArrayBuffer());

            avatarData = Buffer.from(await png.toArrayBuffer());
        }
```

i added console logs everywhere, and it seems to fail at png.toArrayBuffer(). It didn't throw any errors though, just quietly stopped the server action. The try-catch checks if the user has a gravatar, if not: it generates initials. I don't want to use the HTTP API, but i do know it works. Any help would be appreciated.

**Comment by FlorianKoerner** [comment]
Hi @JustZvan 

Unfortunately, I cannot help you with the information provided. Please create a repository where I can reproduce the problem.

I can only tell you that I don't know any framework that causes as many problems as NextJS does. :S
https://github.com/vercel/next.js/discussions/56864

**Comment by JustZvan** [comment]
It seems that converter uses a canvas? Why does it use that on the server? Also, is there any way to bypass this: for example using an alternative library?

**Comment by JustZvan** [comment]
I just used the Sharp library. Now it's working.

**Comment by FlorianKoerner** [comment]
No, we provide a version for the server, but NextJS is the only known platform that apparently cannot distinguish between browser and server and that is exactly the problem.

In the browser we use Canvas, in NodeJS we use resvg-js. This is faster than Sharp.

See:
- https://github.com/dicebear/dicebear/blob/9.x/packages/%40dicebear/converter/src/node/core.ts
- https://github.com/dicebear/dicebear/blob/225c5c35dad751e874769309e59d29b2b9a881bd/packages/%40dicebear/converter/package.json#L21
- https://github.com/yisibl/resvg-js

**Comment by FlorianKoerner** [comment]
If you look in our package.json, you will find the entry point for NodeJS there. Maybe you see the problem why NextJS always uses the wrong entry point?

The funny thing is that users often report that NextJS tries to use the NodeJS entry point in the browser. Your case is exactly the opposite.
