### ISSUE TITLE
HTTP-API fontWeight not working when uses slashes

### ISSUE THREAD

**Issue by stewartorrdefensecom** [DiceBear/avatars#432]
Hi,

Thank you for this API, it looks fantastic. I am looking at using this with Gravatar as a fallback for user avatars. I have read this page that explains how to do this this and for the most part it works:

https://www.dicebear.com/guides/use-the-http-api-as-gravatar-default-image/

I am finding that, when using the slash method instead of querystring, the `fontWeight` option does not seem to work. Here's an example:

https://api.dicebear.com/9.x/initials/png/seed=JD&fontWeight=400&backgroundType=gradientLinear

![avatar400](https://github.com/user-attachments/assets/bc8b9b92-7c5d-4a79-92bc-1a92f17fbf8c)

https://api.dicebear.com/9.x/initials/png/seed=JD&fontWeight=900&backgroundType=gradientLinear

![avatar900](https://github.com/user-attachments/assets/842e41cc-4e59-4371-bbcf-5ef977e13459)

I am using `backgroundType` option to prove that the other seem to work OK. Notice how the `fontWeight` doesn't change.

Is this a bug or intended? 

Thanks!

**Comment by FlorianKoerner** [comment]
Hi @sorr-bulletproof 

We only support the `fontWeight` option in SVG files. The reason for this is that we decided to support only one font weight for performance reasons. Loading and processing fonts is very slow and we prefer to include more subsets rather than one more font weight.
