### ISSUE TITLE
4.0.1 TypeError: random.pickone is not a function

### ISSUE THREAD

**Issue by lockwiser** [DiceBear/avatars#47]
`TypeError: random.pickone is not a function`

`at Object.default_1 [as default] (/demos/node_modules/@dicebear/avatars-avataaars-sprites/lib/utils/getTopType.js:27:32)`
`at default_1 (/demos/node_modules/@dicebear/avatars-avataaars-sprites/lib/index.js:30:136)`

My code:
`var Avatars = require('@dicebear/avatars').default;`
`var sprites = require('@dicebear/avatars-avataaars-sprites').default;`
`var avatars = new Avatars(sprites({}));`

**Comment by FlorianKoerner** [comment]
Which version do you use?

**Comment by FlorianKoerner** [comment]
Please note the changed API since version 4.0.0. Don't call the sprite collection - only pass it.

This should work:

```js
var Avatars = require('@dicebear/avatars').default;
var sprites = require('@dicebear/avatars-avataaars-sprites').default;
var avatars = new Avatars(sprites, {});
```
