### ISSUE TITLE
Reduce API-URL length

### ISSUE THREAD

**Issue by FlorianKoerner** [DiceBear/avatars#55]
We could completely do without the "options" object in the query parameters. We could also use aliases, such as "w" for "width" or "r" for "radius". This shortens the URL, especially for many options.

I would also completely remove the versioning of the API. The versioning (v2) leads to confusion with the library version (e.g. v5).

This is how it looks like:

Before: https://avatars.dicebear.com/v2/male/john-doe.svg?options[radius]=50&options[margin]=3&options[background]=%23ff8000&options[mood][]=happy
After: https://avatars.dicebear.com/api/male/john-doe.svg?r=50&m=3&b=%23ff8000&mood[]=happy

**Comment by sergeevabc** [comment]
Constructing URL is so confusing right now when it comes to multiple options.

**Comment by FlorianKoerner** [comment]
Released with version [4.1.0](https://github.com/DiceBear/avatars/releases/tag/v4.1.0)
