### ISSUE TITLE
Setting *Chance Bottts options to 0 not working

### ISSUE THREAD

**Issue by pennstatephil** [DiceBear/avatars#58]
When I try using the following options (i.e. set any of them to 0, or true for colorful), they don't appear to change the avatar at all for Bottts:

colorful
mouthChance
sidesChance
textureChance
topChange (should this be topChance?)

Also, not sure what the colorful option is supposed to do (maybe exclude grey)?

**Comment by FlorianKoerner** [comment]
Do you have a code example or a sample URL here?

**Comment by pennstatephil** [comment]
You bet!
https://avatars.dicebear.com/v2/bottts/sample.svg?options[mouthChance]=0
https://avatars.dicebear.com/v2/bottts/sample.svg?options[sidesChance]=0
https://avatars.dicebear.com/v2/bottts/sample.svg?options[textureChance]=0
https://avatars.dicebear.com/v2/bottts/sample.svg?options[topChange]=0
None of the above change the image as expected.

I did notice that "colorful" does do something-- changed the top/side colors when value was `1`.

**Comment by FlorianKoerner** [comment]
Released with version [4.1.0](https://github.com/DiceBear/avatars/releases/tag/v4.1.0)
