### ISSUE TITLE
Boolean options don't accept "true" or "false"

### ISSUE THREAD

**Issue by pennstatephil** [DiceBear/avatars#62]
Hi there!
I noticed in the pull request (#61) you had updated the documentation for bottts "colorful" default from 0 to "false". The problem is, when you try to use a string like:

https://avatars.dicebear.com/v2/bottts/example.svg?options[colorful]=true

This error is returned:
```
colorful must be a `number` type, but the final value was: `NaN` (cast from the value `"true"`).
```

Ideally, I think it would accept either `1` or `true`, but as the application sits today, it would be nice to clarify the documentation that you have to use a number rather than a string.

**Comment by FlorianKoerner** [comment]
The documentation is primarily intended for users of the Library and not for users of the HTTP API.

The HTTP API understands '0' as 'false' and '1' as 'true'. It may be necessary to clarify this in the README. Pull Requests are welcome.

But the expected value is correct for now.

See also: https://stackoverflow.com/questions/29739970/how-to-pass-boolean-variable-of-false-in-a-url

**Comment by pennstatephil** [comment]
For sure-- low priority, just figured it might be nice :)
