### ISSUE TITLE
forceUpdate() Warning

### ISSUE THREAD

**Issue by najibghadri** [DiceBear/avatars#67]
Hello!
I am getting this warning in my react app.

index.js:formatted:1 Warning: forceUpdate(...): Can only update a mounting component. This usually means you called forceUpdate() outside componentWillMount() on the server. This is a no-op.

Please check the code for the Selector component.
    in Selector
    in Clothes
    in g
    in g
    in g
    in g
    in svg
    in Avatar
    in AvatarComponent

Can there be something done about it?

**Comment by FlorianKoerner** [comment]
This is an error in a dependency.
See: https://github.com/fangpenlin/avataaars-generator

We are currently rewriting avataaars, so this dependency will soon no longer be necessary. This should also solve the problem.

**Comment by FlorianKoerner** [comment]
Sie Milestone: https://github.com/DiceBear/avatars/milestone/5
