### ISSUE TITLE
While doing server side rendering avatars-jdenticon-sprites causing issues 

### ISSUE THREAD

**Issue by gagan876574** [DiceBear/avatars#68]
While doing renderToString on server side it is giving the following error
```
ReferenceError: btoa is not defined
at Avatars.base64EncodeUnicode (/node_modules/@dicebear/avatars/lib/index.js:168:9)    
at Avatars.create (/node_modules/@dicebear/avatars/lib/index.js:158:80)
```

**Comment by FlorianKoerner** [comment]
`renderToString` is not a function of avatars. You are probably trying to create a base64 string, right?

I can recommend the following workaround.

https://stackoverflow.com/a/38446960

**Comment by gagan876574** [comment]
It worked!

**Comment by FlorianKoerner** [comment]
Ich denke, auf Dauer sollten wir das Problem direkt in der Library angehen.

**Comment by FlorianKoerner** [comment]
`base64` is now deprecated. Use `dataUri` instead.
