### ISSUE TITLE
Initial avatars are not centered in Firefox

### ISSUE THREAD

**Issue by krisu-pl** [DiceBear/avatars#69]
The letters in `initials` type of avatars are not centered vertically but moved to the bottom in Firefox.

![image](https://user-images.githubusercontent.com/7289999/81055392-e2ece200-8ec8-11ea-9c59-5f23868e3049.png)

Browser version: Firefox 75.0

**Comment by FlorianKoerner** [comment]
I can't reproduce it at the moment. Do you have the API URL for me?

![interesting](https://user-images.githubusercontent.com/647303/81058524-e4210d80-8ece-11ea-971c-a1d736a03ab8.PNG)

**Comment by krisu-pl** [comment]
Thanks for a quick response! Strange that you can't reproduce.. Try maybe with a direct url:
https://avatars.dicebear.com/v2/initials/dicebear.svg

Avatar is shown correctly initially but try zooming out to make it smaller - the smaller it is, the bigger the gap from the center.

![image](https://user-images.githubusercontent.com/7289999/81060111-1b44ee00-8ed2-11ea-8eae-5898c31249b4.png)

**Comment by krisu-pl** [comment]
I just checked on Browserstack and the issue appears to be present only on Mac Firefox. Looks fine on Windows. So I guess quite low usage but still maybe worth fixing.

If that's of any help, after our initial investigation we came up with a fix (it requires further testing though):
1. Remove `dy` property
2. Change `dominant-baseline="middle"` to `dominant-baseline="central"`
2. Remove `alignment-baseline="middle"` as it's not part of SVG spec for text

**Comment by FlorianKoerner** [comment]
Thank you for your research. Unfortunately the suggested solution does not work for every browser.

I will also look for a solution here again. The problem can now be reproduced by me on macOS. Windows does not cause any problems.

**Comment by FlorianKoerner** [comment]
Does that work for you?

https://initials-test.floriankoerner.workers.dev/v2/initials/kv.svg

**Comment by krisu-pl** [comment]
It does, indeed! I checked on MacOS Firefox, Safari and Chrome – looks good everywhere. Amazing speed, thanks!

**Comment by FlorianKoerner** [comment]
Released with version [4.1.0](https://github.com/DiceBear/avatars/releases/tag/v4.1.0)
