### ISSUE TITLE
Hijab top mode may apply better

### ISSUE THREAD

**Issue by theMasix** [DiceBear/avatars#72]
Hello. Thanks for awesome API.
But there is an issue with top: ```hijab```.
I think if the ```hijab``` be checked, scarf should be applied anyway.
From my experience, if the avatar has no hair (I mean bald person), scarf won't apply to avatar while I think it should be applied anyway.
Actually, By checking the ```hijab```, scarf should be applied without paying attention to hair! every woman In our country, should have hijab without any exception.

So we can use hijab to specify women.

**Comment by FlorianKoerner** [comment]
Hello @theMasix Thanks for using DiceBear Avatars.
There is a `topChance` Option (default 80%). You could set it to 100. Would that help you?

For example:
https://avatars.dicebear.com/v2/avataaars/test.svg?top[]=hijab&topChance=100&mouth[]=smile

**Comment by theMasix** [comment]
@FlorianKoerner Yes Thanks. It solved my problem.
