### ISSUE TITLE
Can this package be used on a NodeJs server to generate avatar and send it back to clients?

### ISSUE THREAD

**Issue by f6133** [DiceBear/avatars#75]
I am trying to use this package independently of the API, so can it be used locally for a NodeJs server with a Flutter front-end, if not, is there a document i can follow to set up my own API?
Thanks a lot in advance.

**Comment by FlorianKoerner** [comment]
The avatars can be created both on the server (NodeJS) and in the client.
See: https://github.com/DiceBear/avatars/tree/master/packages/avatars#npm

**Comment by f6133** [comment]
I've been trying to get it to work for me for the past two weeks with no luck. I'd thankfully appreciate any kind of help.
I try to use the code suggested on the READ.ME to generate an .svg file inside an ExpressJS server to send it through an API endpoint.

```
import Avatars from '@dicebear/avatars';
import sprites from '@dicebear/avatars-avataaars-sprites';
let options = {};
let avatars = new Avatars(sprites, options);
let svg = avatars.create('custom-seed'); 
```
When I run this code it errors out that `Avatars(sprites, options);` is not a constructor and that I cannot impost outside a module.
So how to simply use this package inside to generate .svg files? And thanks in advance for your time.

**Comment by FlorianKoerner** [comment]
In node you might use "require" instead of "import"? With "require" the following code should work.

```js
const Avatars = require('@dicebear/avatars').default;
const sprites = require('@dicebear/avatars-avataaars-sprites').default;

let options = {};
let avatars = new Avatars(sprites, options);
let svg = avatars.create('custom-seed'); 
```

**Comment by f6133** [comment]
It works, I can't thank you enough. But when I use that code, I get the following warning, how to suppress it? or is it okay to just ignore it? 

```

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: AvatarComponent
    in AvatarComponent
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code from componentWillMount to componentDidMount (preferred in most cases) or the constructor.

Please update the following components: Selector
    in Selector
    in Skin
    in g
    in g
    in g
    in g
    in g
    in svg
    in Avatar
    in AvatarComponent
Warning: forceUpdate(...): Can only update a mounting component. This usually means you called forceUpdate() outside componentWillMount() on the server. This is a no-op.

Please check the code for the Selector component.
    in Selector
    in Clothes
    in g
    in g
    in g
    in g
    in svg
    in Avatar
    in AvatarComponent

```
Again, thank you so much for your time.

**Comment by FlorianKoerner** [comment]
You can ignore the warning.  Will disappear with the upcoming v5 at the end of the year.
