### ISSUE TITLE
Why it always returns random avatar image, it seems options is useless.

### ISSUE THREAD

**Issue by jvlichai** [DiceBear/avatars#80]
`
import Avatars from "@dicebear/avatars";
import sprites from "@dicebear/avatars-avataaars-sprites";

 let options = {'facialHairColor': 'red'};
      let avatars = new Avatars(sprites, options);

      let svg = avatars.create();
`

**Comment by FlorianKoerner** [comment]
You must at least define an empty string as seed.

```
import Avatars from "@dicebear/avatars";
import sprites from "@dicebear/avatars-avataaars-sprites";

let options = {'facialHairColor': 'red'};
let avatars = new Avatars(sprites, options);

let svg = avatars.create('');
```
