### ISSUE TITLE
base64 doesn't work in node

### ISSUE THREAD

**Issue by 5achinJani** [DiceBear/avatars#83]
Error:
![image](https://user-images.githubusercontent.com/23077544/89012576-0bea0b00-d330-11ea-9b87-bf80bc5fcce0.png)

Code:
![image](https://user-images.githubusercontent.com/23077544/89012658-21f7cb80-d330-11ea-8ad3-480e8f10ddff.png)

Node version:  v11.14.0
```json
{
    "ts-node": "^8.6.2",
    "ts-node-dev": "1.0.0-pre.44",
    "typescript": "3.7.5",
}
```

```json
    "@dicebear/avatars": "^4.2.5",
    "@dicebear/avatars-initials-sprites": "^4.2.5",
```
Your documentation says this package is both for browser and node.

**Comment by FlorianKoerner** [comment]
Duplicate #68
