### ISSUE TITLE
Node.js pure backend server, ReferenceError: btoa is not defined

### ISSUE THREAD

**Issue by tomtom94** [DiceBear/avatars#85]
I thought your module was working on a backend Node.js server.

```
ReferenceError: btoa is not defined
at Avatars.base64EncodeUnicode (/node_modules/@dicebear/avatars/lib/index.js:168:9)    
at Avatars.create (/node_modules/@dicebear/avatars/lib/index.js:158:80)
```

I have well seen your comment, you are working on this https://github.com/DiceBear/avatars/issues/68

I'll be happy to see this new module version 

By the way, can you open an opencollective.com account and ask for donation, I'll tip you in. You may need also to publish google ads on your website.

Great module thanks !!

**Comment by FlorianKoerner** [comment]
Version 5.0 is still in active development and will be released early next year. You can follow the development progress here: https://github.com/DiceBear/avatars/tree/v5

Merge requests for version 4.x (for example to correct this bug) are still welcome.
