### ISSUE TITLE
Background color on Avataaars doesn't seem to work

### ISSUE THREAD

**Issue by trymbill** [DiceBear/avatars#86]
I might be misunderstanding the parameters, but I've tried every combination I can imagine and can't get it to work. See: https://avatars.dicebear.com/api/avataaars/test.svg?style=circle&background=%23ff0000 - circle renders with the default blue and not red (i.e. #ff0000).

Based on the code it looks like you're trying to replace #mask-2, but it doesn't seem to be working correctly. I'd love to be able to keep using the API and not have to include the sprites and logic in my own codebase. Any chance for a fix?

**Comment by FlorianKoerner** [comment]
I will take a look

**Comment by FlorianKoerner** [comment]
Should work now.

![](https://avatars.dicebear.com/api/avataaars/test2.svg?style=circle&background=%23ff0000)
