### ISSUE TITLE
My initial sprite via https api broken

### ISSUE THREAD

**Issue by corepay** [DiceBear/avatars#93]
Setup no longer provides first/last initials.  Replaces last initial with `2` instead of real last initial.  appears it is reading the URI encoded value `%20` rather than the initial

You can see issue in your own examples page where John Doe === **J2**

![image](https://user-images.githubusercontent.com/48992923/100599955-0fd66b80-32d7-11eb-86fc-49fb8c495320.png)
![image](https://user-images.githubusercontent.com/48992923/100600030-2250a500-32d7-11eb-91d6-67709fad4cce.png)

**Comment by corepay** [comment]
Direct input to api in browser does not recognize last initial

![image](https://user-images.githubusercontent.com/48992923/100600756-187b7180-32d8-11eb-91a5-de42d2c62bca.png)

![image](https://user-images.githubusercontent.com/48992923/100600877-43fe5c00-32d8-11eb-8465-62f3d8b808f2.png)

**Comment by FlorianKoerner** [comment]
I'm on it.

**Comment by FlorianKoerner** [comment]
<img width="627" src="https://user-images.githubusercontent.com/647303/100602089-bb95b080-3303-11eb-9a6d-ccf75b89eb31.png">

Should be fixed now. Can you confirm this? (empty cache if necessary)

**Comment by corepay** [comment]
Yep - all good again.  Thanks for the great lib and fast response
