### ISSUE TITLE
Avatars with options not displayed

### ISSUE THREAD

**Issue by krisu-pl** [DiceBear/avatars#94]
Avatars with any option parameters are not displayed. To reproduce simply enter your own docs:
![image](https://user-images.githubusercontent.com/7289999/100606009-74aeb780-3311-11eb-93ba-7d6b896af75a.png)
![image](https://user-images.githubusercontent.com/7289999/100606134-a45dbf80-3311-11eb-8237-e20df0039bb8.png)

Test browser: Chrome 87.0.4280.67

**Comment by FlorianKoerner** [comment]
I'm on it.

**Comment by FlorianKoerner** [comment]
<img width="873" alt="Bildschirmfoto 2020-11-30 um 13 14 43" src="https://user-images.githubusercontent.com/647303/100609275-061c2a80-330e-11eb-82c3-d943cd4c8928.png">

Should be fixed. Can you confirm this?

**Comment by krisu-pl** [comment]
Works fine, thanks for resolving this super quickly!
