### ISSUE TITLE
Avataaars only support circle backgrounds. Support for square?

### ISSUE THREAD

**Issue by mikestopcontinues** [DiceBear/avatars#97]
I love what the smaller-than-head circles look like, but I can't support them with my current app. It would be great if I could declare a background on a standard background with the avataaars set. Any chance of that? :)

**Comment by FlorianKoerner** [comment]
Thanks for your bug report. Fixed with v4.5.2

![](https://avatars.dicebear.com/4.5/api/avataaars/john.svg?b=%234e932f)
